### ISSUE TITLE
ip_is_ipv6 error

### ISSUE THREAD

**Issue by dnmfarrell** [tomhrr/p5-Net-IP-XS#2]
```
$ perl -MNet::IP::XS -wE 'say Net::IP::XS->new("2001:db8:85a3::8a2e:370:7334")->ip_is_ipv6;
0

$ perl -MNet::IP::XS -wE 'say $Net::IP::XS::VERSION'
0.20

$ perl -v

This is perl 5, version 26, subversion 0 (v5.26.0) built for x86_64-linux
(with 1 registered patch, see perl -V for more detail)
```

Curiously the internal hash key `ipversion` is set to 6.

Also, the example one liner calls `NI_ip_is_ipv6` three times! The third time is in response to the `ip_is_ipv6` method call, and it returns here:

```
    if (!octs) {                                                                                                                                                              
        return 0;                                                                                                                                                             
    }
```

**Comment by tomhrr** [comment]
> `$ perl -MNet::IP::XS -wE 'say Net::IP::XS->new("2001:db8:85a3::8a2e:370:7334")->ip_is_ipv6;`

`ip_is_ipv6` is part of the procedural interface, rather than the object interface.  It takes a string as its single argument, and returns a boolean indicating whether the string represents an IPv6 address.  To determine the IP version for an object, use the `version` method.

**Comment by tomhrr** [comment]
> Also, the example one liner calls NI_ip_is_ipv6 three times!

Thanks for this.  These calls were unnecessary, and removing them has made object instantiation 5-10% faster.

**Comment by dnmfarrell** [comment]
> ip_is_ipv6 is part of the procedural interface, rather than the object interface

My mistake, apologies and thank you for clarifying.

> removing them has made object instantiation 5-10% faster.

Yay :tada: :+1:
